# Generated by Django 4.1.6 on 2023-02-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("event", models.TextField()),
                ("description", models.TextField()),
                ("price", models.IntegerField(default=0)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLD", "Sold"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.user"
                    ),
                ),
            ],
        ),
    ]
