# Generated by Django 4.1.6 on 2023-03-28 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("user_email", models.CharField(max_length=100)),
                ("event", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=300)),
                ("price", models.IntegerField(default=0)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLD", "Sold"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                ("slug", models.SlugField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="pics")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
