# Generated by Django 4.1.6 on 2023-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="event",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
