# Generated by Django 4.1.6 on 2023-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.TextField(
                choices=[
                    ("Sports", "Sports"),
                    ("Concert", "Concert"),
                    ("Performance", "Performance"),
                    ("Bar", "Bar"),
                    ("Student Group", "Student Group"),
                    ("Other", "Other"),
                ],
                default="Sports",
            ),
        ),
    ]
