# Generated by Django 4.1.6 on 2023-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_token",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
