# Generated by Django 3.2.18 on 2023-03-21 20:33

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20230307_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
