# Generated by Django 4.1.6 on 2023-03-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="event",
            field=models.CharField(max_length=100),
        ),
    ]
