# Generated by Django 3.2.18 on 2023-03-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_listing_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
